name: Cloudflare Pages

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
          cargo build --release --target wasm32-unknown-unknown
          wget https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.11/tailwindcss-extra-linux-x64
          chmod +x ./tailwindcss-extra-linux-x64
          ./tailwindcss-extra-linux-x64 --input ./input.css -o ./tailwind.css --minify
          trunk build --release

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: nxvzbgbfben
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
